name: "Quality"

on: push

jobs:
  linting-and-testing:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        node-version: [18]
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Build
        env:
          CI: true
        run: pnpm build
      - name: Linting & testing
        env:
          CI: true
        run: |
          pnpm lint
          pnpm test
          pnpm type-check
